version: 1.0.{build}
configuration: Release

# scripts to run before build
before_build:
- ps: .\ModifyVersion.ps1 $env:APPVEYOR_BUILD_FOLDER\src\Proverb.Web\Proverb.Web.csproj $env:APPVEYOR_BUILD_NUMBER
- cmd: dotnet restore src\Proverb.Web\Proverb.Web.csproj

build_script:
- cmd: dotnet publish src\Proverb.Web\Proverb.Web.csproj --output %appveyor_build_folder%\dist

test_script:
- cmd: dotnet restore test\Proverb.Web.Tests\Proverb.Web.Tests.csproj
- cmd: dotnet test test\Proverb.Web.Tests\Proverb.Web.Tests.csproj

artifacts:
- path: dist
  name: WebApplication

#######################################
## different deployment environments 
## which can be uncommented to trigger 
## a deployment
#######################################

## proverb-api
environment:
  website_name: proverb-api
  website_psw:
    secure: Kxngm8+WBGPrHffxfy5Ow/rMFy1ZpmyrzTg3iSnUcc7KmVh20PvwVC2erKGVacsOOCTcYCkno+3HME82bhvhPQ==

deploy_script:
- cmd: '"C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:IisApp=''%appveyor_build_folder%\dist'' -dest:IisApp=''%website_name%'',ComputerName=''https://%website_name%.scm.azurewebsites.net/msdeploy.axd'',UserName=''$%website_name%'',Password=''%website_psw%'',IncludeAcls=''False'',AuthType=''Basic'' -enablerule:AppOffline -retryAttempts:2'
