version: 1.0.{build}
configuration: Release

# scripts to run before build
before_build:
- cmd: >-
    dotnet restore src\ProverbApi\ProverbApi.csproj

build_script:
- cmd: >-
    dotnet publish src\ProverbApi\ProverbApi.csproj --output %appveyor_build_folder%\dist

test_script:
  - cmd: dotnet test test\ProverbApi.Tests\ProverbApi.Tests.csproj

artifacts:
- path: dist
  name: WebApplication

#######################################
## different deployment environments 
## which can be uncommented to trigger 
## a deployment
#######################################

## proverb-api
environment:
  website_name: proverb-api
  website_psw:
    secure: Kxngm8+WBGPrHffxfy5Ow/rMFy1ZpmyrzTg3iSnUcc7KmVh20PvwVC2erKGVacsOOCTcYCkno+3HME82bhvhPQ==

deploy_script:
- cmd: '"C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:IisApp=''%appveyor_build_folder%\dist'' -dest:IisApp=''%website_name%'',ComputerName=''https://%website_name%.scm.azurewebsites.net/msdeploy.axd'',UserName=''$%website_name%'',Password=''%website_psw%'',IncludeAcls=''False'',AuthType=''Basic'' -enablerule:AppOffline -retryAttempts:2'
